name: stundenplan
description: Stundenplan-App für FHDW und bib.

version: 3.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  qrcode_reader: ^0.4.4 
  flutter_calendar_carousel: ^1.3.15
  flutter_svg: ^0.12.4
  url_launcher: ^5.0.2
  scoped_model: ^1.0.1
  shared_preferences: ^0.5.2  
  http: ^0.12.0+2
  flutter_platform_widgets: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "launcher_icon" 
  image_path: "assets/icon/icon.png"